config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  resources :musics do
    collection do
      get :search_in_rapid_api
      post :save_music_from_rapid_api
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/music.rb
class Music < ApplicationRecord
	validates :title, :author, :album, :duration, presence: true

	scope :persisted_by_api, -> { where.not(reference_api: nil) }
	scope :persisted_by_system, -> { where(reference_api: nil) }

	def self.ransackable_attributes(auth_object = nil)
    ["album", "author", "title"]
  end

  def persisted_by_system?
  	self.reference_api.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:edit, :update]

  def index
    @q = Music.all.ransack(params[:q])
    @musics = @q.result.order(created_at: :desc).paginate(page: params[:page], per_page: 5)

    respond_to do |format|
      format.html
    end
  end

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(music_params)
    
    respond_to do |format|
      if @music.save
        format.html { redirect_to musics_path, notice: 'Música guardada con éxito.' }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new }     
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit;end

  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to musics_url, notice: 'Música actualizada con éxito.' }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  def search_in_rapid_api
    return redirect_to home_path, alert: 'La búsqueda está vacía.' if params[:keyword].blank?

    page = params[:page] || 1
    per_page = 5
    keyword = params[:keyword]

    results = RapidApiMusicService.new(keyword).call

    results_paginated = WillPaginate::Collection.create(page, per_page, results.length) do |pager| 
      start = (pager.current_page - 1) * pager.per_page
      pager.replace(results[start, pager.per_page] || [])
    end

    respond_to do |format|
      format.html
      format.json { render json: { items: results_paginated, total_pages: results_paginated.total_pages, current_page: results_paginated.current_page }}
    end
  end

  private

  def set_music
    @music = Music.find(params[:id])
  end

  def music_params
    params.require(:music).permit(:title, :author, :album, :duration, :reference_api)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :notice  then "alert-success"
    when :alert   then "alert-danger"
    when :error   then "alert-danger"
    when :warning then "alert-warning"
    when :info    then "alert-info"
    else "alert-primary"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  	<div class="row">
	    <div class="col-md-12">
			<div class="card p-4 mb-4 mx-auto">
				<h2>Buscar musica en RapidApi</h2>
				<br>
				<div class="d-flex justify-content-center align-items-center">
					<input class="form-control" placeholder="ejemplo: Eminem" type="text" id="keyword-rapid-api">
					<div style="margin-right: 10px;"></div>
					<button class="btn btn-primary" id="search-rapid-api">Buscar</button>
				</div>
				<hr class="custom-hr"/>
				<div>
					<table class="table" id="table-results-rapid-api">
						<thead>
							<tr>
								<th scope="col">Titulo</th>
								<th scope="col">Autor</th>
								<th scope="col">Album</th>
								<th scope="col">Duración</th>
								<th scope="col">Acciones</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
					<div id="pagination-controls">
						<button id="prev-page" disabled>Anterior</button>
						<span id="page-number"></span>
						<button id="next-page" disabled>Siguiente</button>
					</div>
				</div>
			</div>
	    </div>
  	</div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		let currentPage = 1;
  		let totalPages = 1;
		$('#search-rapid-api').click(function(){
            keyword = $('#keyword-rapid-api').val();
            loadMusics(currentPage);
		});
		$('#prev-page').on('click', function() {
		    if (currentPage > 1) {
		      loadMusics(currentPage - 1);
		    }
		});
		$('#next-page').on('click', function() {
		    if (currentPage < totalPages) {
		      loadMusics(currentPage + 1);
		    }
		});
		function loadMusics(page){
			$.ajax({
                url: '/musics/search_in_rapid_api',
                dataType: 'json',
                delay: 300,
                data: { keyword: keyword, page: page },
                success: function (data) {
                	$('#table-results-rapid-api tbody').empty();
                    data.items.forEach((music) => {
                    	const musicTr = `
                            <tr>
                                <td>${music.title}</td>
                                <td>${music.author}</td>
                                <td>${music.album}</td>
                                <td>${music.duration}</td>
                                <td>
									<form action="/musics" method="post">
										<input type="hidden" name="music[title]" value="${music.title}">
										<input type="hidden" name="music[author]" value="${music.author}">
										<input type="hidden" name="music[album]" value="${music.album}">
										<input type="hidden" name="music[duration]" value="${music.duration}">
										<input type="hidden" name="music[reference_api]" value="${music.id}">
										<input type="submit" value="Guardar" class="btn btn-success">
									</form>
                                </td>
                            </tr>
                        `;
                        $('#table-results-rapid-api tbody').append(musicTr);
                    });
			        currentPage = data.current_page;
			        totalPages = data.total_pages;
			        updatePaginationControls();
                },
                error: function () {
                    console.error('Failed to load musics.');
                }
            });
		}
		function updatePaginationControls() {
		    $('#prev-page').prop('disabled', currentPage <= 1);
		    $('#next-page').prop('disabled', currentPage >= totalPages);
		    $('#page-number').text(`Pagina ${currentPage} de ${totalPages}`);
		}
	})
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="/">Inicio</a>
                <a class="nav-link" href="/musics">Listado de musica</a>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= content_for(:title) || "Orbits" %></title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= yield :head %>

        <link rel="manifest" href="/manifest.json">
        <link rel="icon" href="/icon.png" type="image/png">
        <link rel="icon" href="/icon.svg" type="image/svg+xml">
        <link rel="apple-touch-icon" href="/icon.png">
        <!-- Load jQuery first -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <!-- Then load Select2 -->
        <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
        <%= javascript_importmap_tags %>
    </head>
    <body class="bg-secondary">
        <div class="custom-container">
            <% flash.each do |type, message| %>
              <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade show" role="alert">
                <%= message %>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            <% end %>
            <%= render 'layouts/header' %>
            <br>
            <%= yield %>
        </div>
    </body>
</html>

app/views/musics/_form.html.erb
<%= simple_form_for @music do |form| %>
    <% if @music.errors.any? %>
        <div class="alert alert-danger" id="error_explanation">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="alert-heading"><%= pluralize(@music.errors.count, "error", plural: "errores") %>:</h4>
            <ul class="mb0">
                <% @music.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="row">
        <div class="col-md-6">
            <%= form.input :title, class: 'form-control' %>    
        </div>
        <div class="col-md-6">
            <%= form.input :album, class: 'form-control' %>    
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <%= form.input :duration, class: 'form-control' %>    
        </div>
        <div class="col-md-6">
            <%= form.input :author, class: 'form-control' %>    
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-1">
            <%= form.button :submit, 'Guardar', class: 'btn btn-success' %>
        </div>
        <div class="col-md-3">
            <%= link_to 'Volver al listado', musics_path, class: 'btn btn-info' %>              
        </div>
    </div>
<% end %>

app/views/musics/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="card p-4 mb-4 mx-auto">
				<h1>Editar musica</h1>
				<hr class="custom-hr"/>
				<br>
				<%= render 'musics/form' %>
			</div>
		</div>
	</div>
</div>

app/views/musics/index.html.erb
<div class="container">
  	<div class="row">
	    <div class="col-md-12">
			<div class="card p-4 mb-4 mx-auto">
				<div class="row">
					<div class="col-md-6">
						<h2>Filtros de búsqueda</h2>
					</div>
					<div class="col-md-6 text-end">
						<%= link_to 'Nueva musica', new_music_path, class: 'btn btn-info' %>
					</div>
				</div>
				<%= search_form_for @q, url: musics_path do |f| %>
					<div class="row">
						<div class="col-md-12">
							<label>Autor</label>
	            			<%= f.search_field :author_eq, class: 'form-control' %>
						</div>
					</div>
					<br>
					<div class="row">
						<div class="col-md-6">
							<label>Titulo</label>
	            			<%= f.search_field :title_eq, class: 'form-control' %>
						</div>
						<div class="col-md-6">
							<label>Album</label>
	            			<%= f.search_field :album_eq, class: 'form-control' %>
						</div>
					</div>
					<br>
					<div class="row">
			            <div class="col-md-1">
                            <%= f.submit 'Buscar', :class => "btn btn-primary" %>
                        </div>
                        <div class="col-md-3" style="margin-left: -20px;">
                        	<%= link_to 'Limpiar filtros', musics_path, class: 'btn btn-danger' %>
                        </div>
					</div>
				<% end %>
				<hr class="custom-hr" />
				<div class="table-responsive" style="max-height: 400px; overflow-y: auto;">
					<table class="table table-striped table-hover" id="table-results-rapid-api">
						<thead>
							<tr>
								<th scope="col">Titulo</th>
								<th scope="col">Autor</th>
								<th scope="col">Album</th>
								<th scope="col">Duración</th>
								<th scope="col">¿Creado por sistema?</th>
								<th scope="col">Acciones</th>
							</tr>
						</thead>
						<tbody>
							<% @musics.map do |music| %>
								<tr>
									<td><%= music.title %></td>
									<td><%= music.author %></td>
									<td><%= music.album %></td>
									<td><%= music.duration %></td>
									<td><%= music.persisted_by_system? ? 'Si' : 'No' %></td>
									<td>
										<%= link_to 'Editar', edit_music_path(music), class: 'btn btn-info' %>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
				<div class="text-left my-4">
		            <div class="digg_pagination">
		              <%= will_paginate @musics, :container => false %>
		            </div>
		        </div>
			</div>
	    </div>
  	</div>
</div>

app/views/musics/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="card p-4 mb-4 mx-auto">
				<h1>Nueva musica</h1>
				<hr class="custom-hr"/>
				<br>
				<%= render 'musics/form' %>
			</div>
		</div>
	</div>
</div>